//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MitchellProjectClient.ClaimsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Claim", Namespace="http://schemas.datacontract.org/2004/07/MitchellProject")]
    [System.SerializableAttribute()]
    public partial class Claim : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AdjusterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaimNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LossDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AdjusterId {
            get {
                return this.AdjusterIdField;
            }
            set {
                if ((this.AdjusterIdField.Equals(value) != true)) {
                    this.AdjusterIdField = value;
                    this.RaisePropertyChanged("AdjusterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimNumber {
            get {
                return this.ClaimNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimNumberField, value) != true)) {
                    this.ClaimNumberField = value;
                    this.RaisePropertyChanged("ClaimNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LossDate {
            get {
                return this.LossDateField;
            }
            set {
                if ((object.ReferenceEquals(this.LossDateField, value) != true)) {
                    this.LossDateField = value;
                    this.RaisePropertyChanged("LossDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClaimsService.ClaimsService")]
    public interface ClaimsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClaimsService/CreateClaim", ReplyAction="http://tempuri.org/ClaimsService/CreateClaimResponse")]
        string CreateClaim(MitchellProjectClient.ClaimsService.Claim claim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClaimsService/CreateClaim", ReplyAction="http://tempuri.org/ClaimsService/CreateClaimResponse")]
        System.Threading.Tasks.Task<string> CreateClaimAsync(MitchellProjectClient.ClaimsService.Claim claim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClaimsService/CreateClaimFromXML", ReplyAction="http://tempuri.org/ClaimsService/CreateClaimFromXMLResponse")]
        string CreateClaimFromXML(string xmlddoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClaimsService/CreateClaimFromXML", ReplyAction="http://tempuri.org/ClaimsService/CreateClaimFromXMLResponse")]
        System.Threading.Tasks.Task<string> CreateClaimFromXMLAsync(string xmlddoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClaimsService/testSQL", ReplyAction="http://tempuri.org/ClaimsService/testSQLResponse")]
        string testSQL(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClaimsService/testSQL", ReplyAction="http://tempuri.org/ClaimsService/testSQLResponse")]
        System.Threading.Tasks.Task<string> testSQLAsync(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClaimsService/testXML", ReplyAction="http://tempuri.org/ClaimsService/testXMLResponse")]
        string testXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClaimsService/testXML", ReplyAction="http://tempuri.org/ClaimsService/testXMLResponse")]
        System.Threading.Tasks.Task<string> testXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClaimsService/readClaim", ReplyAction="http://tempuri.org/ClaimsService/readClaimResponse")]
        string readClaim(string claimnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClaimsService/readClaim", ReplyAction="http://tempuri.org/ClaimsService/readClaimResponse")]
        System.Threading.Tasks.Task<string> readClaimAsync(string claimnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClaimsService/deleteClaim", ReplyAction="http://tempuri.org/ClaimsService/deleteClaimResponse")]
        string deleteClaim(string claimnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClaimsService/deleteClaim", ReplyAction="http://tempuri.org/ClaimsService/deleteClaimResponse")]
        System.Threading.Tasks.Task<string> deleteClaimAsync(string claimnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClaimsService/readVehicleFromClaim", ReplyAction="http://tempuri.org/ClaimsService/readVehicleFromClaimResponse")]
        string readVehicleFromClaim(string claimnumber, string vehicle_vin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClaimsService/readVehicleFromClaim", ReplyAction="http://tempuri.org/ClaimsService/readVehicleFromClaimResponse")]
        System.Threading.Tasks.Task<string> readVehicleFromClaimAsync(string claimnumber, string vehicle_vin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClaimsService/getClaimsInDateRange", ReplyAction="http://tempuri.org/ClaimsService/getClaimsInDateRangeResponse")]
        string[] getClaimsInDateRange(string startdate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClaimsService/getClaimsInDateRange", ReplyAction="http://tempuri.org/ClaimsService/getClaimsInDateRangeResponse")]
        System.Threading.Tasks.Task<string[]> getClaimsInDateRangeAsync(string startdate, string enddate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClaimsServiceChannel : MitchellProjectClient.ClaimsService.ClaimsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClaimsServiceClient : System.ServiceModel.ClientBase<MitchellProjectClient.ClaimsService.ClaimsService>, MitchellProjectClient.ClaimsService.ClaimsService {
        
        public ClaimsServiceClient() {
        }
        
        public ClaimsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClaimsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClaimsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClaimsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateClaim(MitchellProjectClient.ClaimsService.Claim claim) {
            return base.Channel.CreateClaim(claim);
        }
        
        public System.Threading.Tasks.Task<string> CreateClaimAsync(MitchellProjectClient.ClaimsService.Claim claim) {
            return base.Channel.CreateClaimAsync(claim);
        }
        
        public string CreateClaimFromXML(string xmlddoc) {
            return base.Channel.CreateClaimFromXML(xmlddoc);
        }
        
        public System.Threading.Tasks.Task<string> CreateClaimFromXMLAsync(string xmlddoc) {
            return base.Channel.CreateClaimFromXMLAsync(xmlddoc);
        }
        
        public string testSQL(int i) {
            return base.Channel.testSQL(i);
        }
        
        public System.Threading.Tasks.Task<string> testSQLAsync(int i) {
            return base.Channel.testSQLAsync(i);
        }
        
        public string testXML() {
            return base.Channel.testXML();
        }
        
        public System.Threading.Tasks.Task<string> testXMLAsync() {
            return base.Channel.testXMLAsync();
        }
        
        public string readClaim(string claimnumber) {
            return base.Channel.readClaim(claimnumber);
        }
        
        public System.Threading.Tasks.Task<string> readClaimAsync(string claimnumber) {
            return base.Channel.readClaimAsync(claimnumber);
        }
        
        public string deleteClaim(string claimnumber) {
            return base.Channel.deleteClaim(claimnumber);
        }
        
        public System.Threading.Tasks.Task<string> deleteClaimAsync(string claimnumber) {
            return base.Channel.deleteClaimAsync(claimnumber);
        }
        
        public string readVehicleFromClaim(string claimnumber, string vehicle_vin) {
            return base.Channel.readVehicleFromClaim(claimnumber, vehicle_vin);
        }
        
        public System.Threading.Tasks.Task<string> readVehicleFromClaimAsync(string claimnumber, string vehicle_vin) {
            return base.Channel.readVehicleFromClaimAsync(claimnumber, vehicle_vin);
        }
        
        public string[] getClaimsInDateRange(string startdate, string enddate) {
            return base.Channel.getClaimsInDateRange(startdate, enddate);
        }
        
        public System.Threading.Tasks.Task<string[]> getClaimsInDateRangeAsync(string startdate, string enddate) {
            return base.Channel.getClaimsInDateRangeAsync(startdate, enddate);
        }
    }
}
